apiVersion: v1
kind: Secret
metadata:
  name: users-secrets
  namespace: users
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Server=DB_HOST,1433;Database=UsersDb;User Id=sa;Password=StrongPassword;"
  JwtSettings__Secret: "replace-with-strong-jwt-secret"
  JwtSettings__Issuer: "your-issuer"
  JwtSettings__Audience: "your-audience"