apiVersion: v1
kind: ConfigMap
metadata:
  name: users-service-config
  namespace: production
data:
  # Configurações da aplicação
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:8080"
  
  # Swagger
  SwaggerBasePath: "/users"
  
  # AWS Configuration
  AWS_REGION: "us-east-1"
  
  # SQS Configuration
  SQS_AUTHENTICATION_REQUEST_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/680852412198/fcg-auth-requests-queue"
  
  # SNS Configuration
  SNS_AUTHENTICATION_RESPONSE_TOPIC_ARN: "arn:aws:sns:us-east-1:680852412198:fcg-auth-responses"
  
  # Serilog Configuration
  Serilog__MinimumLevel__Default: "Information"
  Serilog__MinimumLevel__Override__Microsoft: "Warning"
  Serilog__MinimumLevel__Override__System: "Warning"
  
  # OpenTelemetry Configuration
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
  OTEL_SERVICE_NAME: "users-service"
  OTEL_SERVICE_VERSION: "1.0.0"
  
  # Health Check Configuration
  HealthChecks__UI__PollingInterval: "10"
  HealthChecks__UI__EvaluationTimeInSeconds: "10"
  
  # JWT Settings (não sensíveis)
  JwtSettings__Issuer: "CloudGamesAPI"
  JwtSettings__Audience: "CloudGamesClient"
  JwtSettings__ExpirationInMinutes: "60"