name: CD - Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Instalar SDK do .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Docker Login
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Users API
        uses: docker/build-push-action@v6.18.0
        with:
          tags: '${{ secrets.DOCKER_USERNAME }}/tech-challenge-users-alpine:latest'
          context: .
          push: true

      - name: Build and push Prometheus
        uses: docker/build-push-action@v6.18.0
        with:
          tags: '${{ secrets.DOCKER_USERNAME }}/tech-challenge-prometheus:latest'
          context: .
          file: monitoring/Dockerfile.prometheus
          push: true

      - name: Build and push Grafana
        uses: docker/build-push-action@v6.18.0
        with:
          tags: '${{ secrets.DOCKER_USERNAME }}/tech-challenge-grafana:latest'
          context: .
          file: Dockerfile.grafana
          push: true

      - name: Build and push ADOT Collector
        uses: docker/build-push-action@v6.18.0
        with:
          tags: '${{ secrets.DOCKER_USERNAME }}/tech-challenge-adot-collector:latest'
          context: .
          file: observability/Dockerfile.adot-collector
          push: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Update ECS Users service
        run: |
          aws ecs update-service \
            --cluster fcg-cluster \
            --service fcg-users-task-service-57hptthy \
            --force-new-deployment \
            --region us-east-1

      - name: Update ECS Observability service
        run: |
          aws ecs update-service \
            --cluster fcg-cluster \
            --service fcg-observability-service-y1cnk5b3 \
            --force-new-deployment \
            --region us-east-1
